"""Generate a QWERTY keyboard as a MuJoCo `mujocoinclude` fragment.

Each key is an independent body on a prismatic (slide) joint with a return
spring, a box geom, a top site, and a `touch` sensor. A "keypress" is detected
either from the key travel (slide qpos past a threshold) or from the touch
sensor contact force. The generated fragment is included by
`myohand_keyboard.xml`.

Run:  python make_keyboard.py            # writes qwerty_keyboard.xml
Layout coordinates:  x = across keyboard (columns), y = rows (near->far),
z = up (keys travel down in -z when pressed).
"""
from __future__ import annotations

import argparse
import os

# Standard staggered QWERTY. Each entry: (label, width_in_units).
# `label` is the emg2qwerty-style key name; width in key-pitch units.
ROWS: list[list[tuple[str, float]]] = [
    [("`", 1), ("1", 1), ("2", 1), ("3", 1), ("4", 1), ("5", 1), ("6", 1),
     ("7", 1), ("8", 1), ("9", 1), ("0", 1), ("-", 1), ("=", 1),
     ("Key.backspace", 2)],
    [("Key.tab", 1.5), ("q", 1), ("w", 1), ("e", 1), ("r", 1), ("t", 1),
     ("y", 1), ("u", 1), ("i", 1), ("o", 1), ("p", 1), ("[", 1), ("]", 1),
     ("\\", 1.5)],
    [("Key.caps_lock", 1.75), ("a", 1), ("s", 1), ("d", 1), ("f", 1),
     ("g", 1), ("h", 1), ("j", 1), ("k", 1), ("l", 1), (";", 1), ("'", 1),
     ("Key.enter", 2.25)],
    [("Key.shift", 2.25), ("z", 1), ("x", 1), ("c", 1), ("v", 1), ("b", 1),
     ("n", 1), ("m", 1), (",", 1), (".", 1), ("/", 1), ("Key.shift_r", 2.75)],
    [("Key.space", 8.0)],
]

# Left edge offset (in units) of each row, giving the classic stagger.
ROW_STAGGER = [0.0, 0.0, 0.25, 0.75, 3.5]


def sanitize(label: str) -> str:
    """Map a key label to a MuJoCo-safe unique name."""
    special = {
        "`": "backtick", "-": "minus", "=": "equal", "[": "lbracket",
        "]": "rbracket", "\\": "backslash", ";": "semicolon",
        "'": "quote", ",": "comma", ".": "period", "/": "slash",
    }
    if label in special:
        return special[label]
    if label.startswith("Key."):
        return label[4:]  # Key.space -> space
    return label  # letters / digits


def generate(
    pitch: float = 0.019,     # 19.05 mm real key pitch
    gap: float = 0.002,       # gap between keycaps
    travel: float = 0.004,    # key travel depth (m)
    cap_height: float = 0.004,
    base_pos=(-0.325, -0.600, 1.380),  # keyboard body world origin (under hand)
    stiffness: float = 80.0,   # key return spring
    damping: float = 1.0,
) -> str:
    half = (pitch - gap) / 2.0
    bodies: list[str] = []
    sensors: list[str] = []
    keymap: list[str] = []  # comment listing label -> name

    y = 0.0
    # rows are laid out far (number row) to near (space); flip so row0 is far
    n_rows = len(ROWS)
    for r, row in enumerate(ROWS):
        # y increases toward the user; put number row at far (largest y)
        row_y = (n_rows - 1 - r) * pitch
        x = ROW_STAGGER[r] * pitch
        for label, width in row:
            w_half = (width * pitch - gap) / 2.0
            cx = x + w_half  # center of this (possibly wide) key
            name = sanitize(label)
            # position relative to the keyboard body (which is placed at base_pos)
            gpos = f"{cx:.5f} {row_y:.5f} {cap_height/2:.5f}"
            # gravcomp="1" keeps the key from sagging under gravity so it rests
            # at the top of its travel until a finger presses it.
            bodies.append(f"""      <body name="key_{name}" pos="{gpos}" gravcomp="1">
        <joint name="key_{name}_slide" type="slide" axis="0 0 -1" range="0 {travel:.4f}"
               stiffness="{stiffness}" damping="{damping}" springref="0" armature="0.0005"/>
        <geom name="key_{name}_geom" type="box" size="{w_half:.5f} {half:.5f} {cap_height/2:.5f}"
              rgba="0.15 0.15 0.17 1" mass="0.005" friction="1 0.005 0.0001"/>
        <site name="key_{name}_site" type="box" size="{w_half:.5f} {half:.5f} {cap_height/2:.5f}"
              rgba="0.3 0.6 0.9 0.15"/>
      </body>""")
            sensors.append(f'    <touch name="key_{name}_touch" site="key_{name}_site"/>')
            keymap.append(f"{label} -> key_{name}")
            x += width * pitch

    body_xml = "\n".join(bodies)
    sensor_xml = "\n".join(sensors)
    keymap_comment = "\n".join("       " + k for k in keymap)

    return f"""<mujocoinclude model="qwerty_keyboard">
<!-- AUTO-GENERATED by make_keyboard.py. Do not edit by hand.
     pitch={pitch} gap={gap} travel={travel} cap_height={cap_height}
     Key label -> body name:
{keymap_comment}
-->
  <worldbody>
    <body name="keyboard" pos="{base_pos[0]:.4f} {base_pos[1]:.4f} {base_pos[2]:.4f}">
      <!-- Decorative base plate (contype/conaffinity=0 -> no collision, so it
           never blocks key travel or spawns key-plate contacts). Sits below the
           key's lowest travel point. -->
      <geom name="keyboard_plate" type="box" contype="0" conaffinity="0"
            size="0.16 0.06 0.004" pos="0.14 0.038 -0.012"
            rgba="0.08 0.08 0.09 1" mass="1.0"/>
{body_xml}
    </body>
  </worldbody>
  <sensor>
{sensor_xml}
  </sensor>
</mujocoinclude>
"""


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(os.path.dirname(__file__), "qwerty_keyboard.xml"))
    args = ap.parse_args()
    xml = generate()
    with open(args.out, "w") as f:
        f.write(xml)
    n_keys = sum(len(r) for r in ROWS)
    print(f"wrote {args.out} ({n_keys} keys)")
